export const TILE_PX = 32;
export const GAME_X_T = 16;
export const GAME_Y_T = 15;
export const GAME_X_PX = GAME_X_T * TILE_PX;
export const GAME_Y_PX = GAME_Y_T * TILE_PX;
export const BATTLE_FIELD_X_T = 13;
export const BATTLE_FIELD_Y_T = 14;
export const BATTLE_FIELD_X_PX = BATTLE_FIELD_X_T * TILE_PX;
export const BATTLE_FIELD_Y_PX = BATTLE_FIELD_Y_T * TILE_PX;
